### ISSUE TITLE
[Bug] Javacript Error on launch while minimized

### ISSUE THREAD

**Issue by 17hoehbr** [Apple-Music-Electron/Apple-Music-Electron#100]
I'm running this on Arch Linux using the AUR package I built here: https://aur.archlinux.org/packages/apple-music-electron
Basically this just compiles it as normal and installs to the filesystem using the compiled binaries in the /dist/linux-unpacked folder.

Anyway when I launch the application using the apple-music-electron.desktop file provided in that AUR package it launches just fine, and when I close the application it minimizes to the system tray as normal. If I click the tray icon and press Show Apple Music it again restores the window just fine, but if I try to launch it from the .desktop file while the app is already running in the tray I get the following javascript error:

>A JavaScript error occurred in the main process
>Uncaught Exception:
>TypeError: app.setUserTasks is not a function
>at App.<anonymous>(/opt/apple-music-electron/resources/app.asar/index.js:69:17)
>at App.emit(events.js:315:20)

This error does not seem to happen in the AppImage release however. It's very possible that it's an error in my part with the AUR package but I'm not sure what could be causing it.

**Comment by coredev-uk** [comment]
setUserTasks is only used in one place, when the application is ready. So when you are launching it through the desktop file, it is skipping and/or not recognising the existing instance, and proceeds to make a new application instance. The weird thing is that as you are doing this on Linux, it should not be an issue as setUserTasks is a Windows function and a check is done on the platform in the function.
