### ISSUE TITLE
[Feature Request] Scroll Bar

### ISSUE THREAD

**Issue by 17hoehbr** [Apple-Music-Electron/Apple-Music-Electron#102]
I noticed that there is no scroll bar in the application. I understand that this was done because the default electron scroll bar is pretty ugly compared to Apple standards, however an Apple style scrollbar can be implemented via CSS. This was a feature in my version that I'd be happy to merge in after I look into how CSS is handled in this application.

**Comment by 17hoehbr** [comment]
I'm thinking it would probably be best to make this a .js script so that it persists through themes, but would custom themes then be able to design their own scroll bar as well or would the .js script overwrite it? Ideally I think I'd want the scroll bar to persist across css themes unless explicitly modified by the theme creator but I'm not sure how to go about that. For now I think I'll just do it as a .js script and hopefully get to making it possible to disable scripts via the settings menu issue.

**Comment by 17hoehbr** [comment]
I see now that there is a setting that disabled the scrollbar, but I still think it would be nice to  replace the scrollbar with an Apple-esque style one. If I understand the code correctly and please correct me if I'm wrong, as long as the script to inject custom scrollbar css is loaded before the theme is loaded, then the scrollbar will persist through all themes unless said theme explicitly changes the scrollbar functionality right? I'm not very familiar with using javascript to inject CSS however I do have the following CSS code which creates a nice Apple-esque scrollbar:

```
/* total width */
::-webkit-scrollbar {
  width: 12px;
}

/* scrollbar itself */
::-webkit-scrollbar-thumb {
  background-color: #babac0;
  border-radius: 16px;
}

/* hide scrollbar buttons */
::-webkit-scrollbar-button {
  display:none;
}
/* no scrollbar in menu area */
div {
  overflow: hidden;
}

div.web-navigation__scrollable {
  overflow: auto;
}

div.loading-inner {
  overflow: auto;
}
```

And here are examples of how it looks in my older app:
![preview.png](https://raw.githubusercontent.com/17hoehbr/apple-music-electron/master/preview.png)
![preview_dark.png](https://raw.githubusercontent.com/17hoehbr/apple-music-electron/master/preview_dark.png)

Although if we are using javascript anyway we could probably do something even fancier, but again I'm not sure how to go about that.

**Comment by coredev-uk** [comment]
I did experiment with adding a scrollbar like what you've got there and it is currently in the development build - however I did encounter various issues with the scrollbar going inside the media player and the height of the bar being too big. I'll give your one a test and get back to you.

**Comment by 17hoehbr** [comment]
The "no scrollbar in menu area" section should fix that bug iirc

**Comment by coredev-uk** [comment]
This was not completed.

**Comment by cryptofyre** [comment]
Seeing as there’s a scroll bar enabling option in settings now i’m closing this.
