### ISSUE TITLE
Add support for Chromecast devices

### ISSUE THREAD

**Issue by Adil-MohammedK** [Apple-Music-Electron/Apple-Music-Electron#116]

**Comment by coredev-uk** [comment]
Unsure if this is even possible

**Comment by Adil-MohammedK** [comment]
There are few python libraries and softwares which can emulate an Airplay sender. Could use those

**Comment by child-duckling** [comment]
We use node.js...

There isn't any airplay libraries that 1. are in js 2. have been updated and 3. are NOT react based
https://www.npmjs.com/search?q=airplay&ranking=maintenance

**Comment by devilAPI** [comment]
https://nto.github.io/AirPlay.html

**Comment by cryptofyre** [comment]
more painful then what its worth.

**Comment by child-duckling** [comment]
> https://nto.github.io/AirPlay.html

... updated in 2012

**Comment by Nosh118** [comment]
> ... last updated in 2012

Sidenote: how the fuck was 2012 9 years ago?

**Comment by child-duckling** [comment]
also there's AirPlay2!

**Comment by devilAPI** [comment]
https://github.com/openairplay/openairplay

**Comment by child-duckling** [comment]
This is Linux only, and in Python. 

To make this work reliably across multiple platforms, we would need a node.js package. It would be a lot easier to implement it cause our codebase is in node.js (hence all the .js files) and our build system, the one that turns code into .exe/.app/.snap files, is also in node.js. To implement something that's not node.js into a node.js project is difficult to say the least. **It would be way too much work for a small feature**


If you want to do the work, go at it, and we'll await the PR.

**Comment by child-duckling** [comment]
Closing, but will open once the required dependencies are found / PR is opened

**Comment by child-duckling** [comment]
Found a solution (maybe). Will attempt for 3.0 or 3.1.
