### ISSUE TITLE
Window positioning

### ISSUE THREAD

**Issue by mysteriously** [Apple-Music-Electron/Apple-Music-Electron#117]
Hello,

I have multiple displays and have the app on screen on the left and it is maximized. However if I close it and reopen, it shows up on main screen and not maximized. I enabled close on exit (x).
Not a big deal if you ask me - I don't mind it at all. Just wanted to let you know.
"emulateMacOS": false,
Windows 10 x64 - latest

I am unable to force language to English. I've tried en, en-us etc with and without quotes but nothing worked.

Thank you so much for the great app!

**Comment by coredev-uk** [comment]
We can add a configuration option to maximize on window restore if you'd like. However, this can be very annoying. Usually restoring an app should put it on the monitor it was on. Do you have closeButtonMinimize turned on?

**Comment by mysteriously** [comment]
I have 3 displays.
No, I changed it.
"closeButtonMinimize": false,

**Comment by coredev-uk** [comment]
I'm not sure if we can save the window position for the next launch. If you'd like it to reopen on the same monitor, just turn on closeButtonMinimize. There isn't much more I can suggest.
