### ISSUE TITLE
[Bug] Resizable window from top when using macosAppEmu / custom frame

### ISSUE THREAD

**Issue by coredev-uk** [Apple-Music-Electron/Apple-Music-Electron#121]
We need this but idk how

![image](https://user-images.githubusercontent.com/64542347/124978775-1cb7fc00-e02a-11eb-8174-afdc78c0a374.png)

**Comment by child-duckling** [comment]
'resizable: true'?

**Comment by coredev-uk** [comment]
already enabled, but does not recognise the macos frame

**Comment by child-duckling** [comment]
https://stackoverflow.com/a/32897808

**Comment by child-duckling** [comment]
https://stackoverflow.com/a/32897808

when you mark a window as "frame: false" and then enable "-webkit-app-region: drag", the drag flag disables the window-resize-handles.
