### ISSUE TITLE
Unable to fetch error

### ISSUE THREAD

**Issue by mysteriously** [Apple-Music-Electron/Apple-Music-Electron#125]
Hi,

1) Run Apple Music Electron
2) Put Windows PC to sleep state
3) Wake it up
4) Apple Music Electron shows unable to fetch error

**Comment by child-duckling** [comment]
Doing CTRL/⌘ + R fixes this issue.

**Comment by coredev-uk** [comment]
*Only works if devTools is turned on*

**Comment by mysteriously** [comment]
It happens when you loose internet connection for a moment

**Comment by mysteriously** [comment]
2.41 Windows x64, still see the error after waking up the computer from sleep mode.

**Comment by coredev-uk** [comment]
If you could get me the class name of the fetch error window that'd be great, then I might be able to put a fix in for this.

**Comment by mysteriously** [comment]
Sure, just please let me know how to do that. I like testing stuff but I am not a programist.

**Comment by mysteriously** [comment]
https://i.imgur.com/0Ikpwar.png

**Comment by coredev-uk** [comment]
in the settings, go to advanced and turn on dev tools then relaunch and when the error occurs right click on the box and click inspect element then screenshot what it says on the right side of your screen.

**Comment by mysteriously** [comment]
https://i.imgur.com/nZv5L3A.png
https://i.imgur.com/QVduEbX.png
