### ISSUE TITLE
yay -S apple-music-electron does not install

### ISSUE THREAD

**Issue by nghtstr** [Apple-Music-Electron/Apple-Music-Electron#132]
I am running Arch, and when I do the following command to install this package:

`yay -S apple-music-electron` I get the following error:

```
install: cannot stat '/home/mike/.cache/yay/apple-music-electron/src/Apple-Music-Electron-2.3.0/assets/icon.png': No such file or directory
```

Any help would be greatly appreciated!

**Comment by Miguelkarp** [comment]
I think using yay don´t let you edit the config file, so when the compilation process run, you can't modify the order to change the icons path. I solve it just (during the compilation process ) create that directory and paste the icons from /Apple-Music-Electron-2.3.0/resources/icons to the new directory /Apple-Music-Electron-2.3.0/assets/. 
It's important doing when the compile process is running bc if you do it before, yay delete the Apple Music directory and download again from github.

**Comment by Miguelkarp** [comment]
Another thing i recommended is download directly the Source Code and compiling by yourself, it's very easy and you can include the changes from 2.4V to make sure running without issues.

**Comment by fridtjof** [comment]
A workaround until it's fixed upstream:

- Download the PKGBUILD with `yay -U apple-music-electron`. It'll create a directory with the same name, and the PKGBUILD in it
- enter the created directory
- apply the attached patch to the PKGBUILD like so: `patch PKGBUILD <path to patch file>`
- build the package by running `makepkg -s`
- install the resulting .pkg.zst (or other file extension depending on default compression) with `yay -U <file name>`

[fix-build-and-update-to-2.4.0.txt](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/6933600/fix-build-and-update-to-2.4.0.txt)

**Comment by cryptofyre** [comment]
Great work! Ill try and get this pushed to the AUR package ASAP.

**Comment by coredev-uk** [comment]
Another alternative is that we release a pacman package on GitHub and with that you can just do yay -U *Pac-Man file name*

**Comment by coredev-uk** [comment]
I currently have access to the AUR package, I suggest using the [git package](https://aur.archlinux.org/packages/apple-music-electron-git) until the next version is released. The `apple-music-electron` package uses the archive file made on release and the one made with 2.5.0 was outdated.
