### ISSUE TITLE
Little bug and add Order

### ISSUE THREAD

**Issue by RebellionBritney** [Apple-Music-Electron/Apple-Music-Electron#134]
When I click in one song to play it, other song is selected, so I need to scroll down and press play again and the next song is the one who is being played and it didn't save the last list I played and if I had the shuffle activated or not. Other bug is that songs loaded too slow and take load of time to start and that mess with songs that needs gapless playback. Also, I think it would be useful if you could order your saved songs to Artists, Album, Recently added, etc. and not just in Songs alphabetical order.

**Comment by child-duckling** [comment]
> When I click in one song to play it, other song is selected, so I need to scroll down and press play again and the next song is the one who is being played and it didn't save the last list I played and if I had the shuffle activated or not.

Have you tried reinstalling the app

> Other bug is that songs loaded too slow and take load of time to start and that mess with songs that needs gapless playback. 
That's 🍎 for you :/

> Also, I think it would be useful if you could order your saved songs to Artists, Album, Recently added, etc. and not just in Songs alphabetical order.
Due to the way Apple have their website, and we have our app, this may not be possible to do.

**Comment by SubZeroNexii** [comment]
> > When I click in one song to play it, other song is selected, so I need to scroll down and press play again and the next song is the one who is being played and it didn't save the last list I played and if I had the shuffle activated or not.
> 
> Have you tried reinstalling the app

This is actually an website issue. I have the exact same issue on chrome and firefox. The other song is selected issue only happens once when the website is loaded. It then works normally. Still really annoying.

There's also an app related issue in which the webpage gives an "this song cannot be played in your country" error after the first log in. The only fix I found is to reload the app and it never does it again.

**Comment by coredev-uk** [comment]
Regarding most of your requests in this issue, not much can be done by us, unfortunately. The best suggestion is to make a feedback form [here](https://www.apple.com/feedback/apple-music.html) and maybe they'll listen.
