### ISSUE TITLE
Dynamic buttons

### ISSUE THREAD

**Issue by child-duckling** [Apple-Music-Electron/Apple-Music-Electron#145]
Hello !
As a recent Apple music subscriber, i was previously using spotify and [spicetify](https://github.com/khanhas/spicetify-cli) (spotify customization tool), which has "custom Apps" and "extensions" to add features to the spotify client. 
Could it be possible to have, for example, a "Lyrics" button somewhere in the app linked to [Genius](https://docs.genius.com/) or _**even better**_ [Musixmatch ](https://developer.musixmatch.com/)for synced lyrics ? 
I customized my spicetify to make it as i wanted so i think i will _attempt_ to look and fiddle around the source code, but i think it could be a great feature to add to the app ! 
Anyways, congrats to the dev, i really appreciate the application :)

I also "made" in spicetify a dynamic theme which changed the accent color of all buttons and icons according to the vibrant color of the album cover. The main background color was like a dark grey, tinted to the second vibrant color. That could look slick in the apple music interface too...

_Originally posted by @jairaume in https://github.com/cryptofyre/Apple-Music-Electron/discussions/144_

**Comment by coredev-uk** [comment]
We already do this, themes in spicetify use JS files that are injected into the UI. We do the same for all the extensions we use (MacOSAppEmu, settings Button etc.). We can make it so the user can create their own and inject it into their app. Regarding your suggestion, it's already been suggested in #44 and we aim to add it in the future. With dynamic themes, I wouldn't be surprised if there was a module for this. But themes are already available for users to create and edit however they'd like.

**Comment by jairaume** [comment]
Ok cool thank you very much for your answer im looking forward to it ! 
I believe making the js for the dynamic theme isn't too hard i would personally take my former dynamic theme for spicetify and re arrange it somehow... it used some kind of color extractor built in spicetify tho..

**Comment by coredev-uk** [comment]
No further discussion is needed. Closing issue.
