### ISSUE TITLE
[Bug] Visual Issues when macOS Music Emulation is set to Right

### ISSUE THREAD

**Issue by IsaacMarovitz** [Apple-Music-Electron/Apple-Music-Electron#147]
When you set macOS Music Emulation to Right, the 'App Settings' button doesn't appear and there is missing padding above the 'Up Next' menu: https://imgur.com/rxuZwSj

Occurs in v2.4.0 on Windows 11.

**Comment by coredev-uk** [comment]
Right align is something we look to improve upon, for now I suggest you use left align or disable it.￼￼￼￼

**Comment by jaksart1** [comment]
@coredev-uk I'm having this same issue, but I can't figure out how to disable it or switch back to left align without the settings menu. Reinstalling does not help
