### ISSUE TITLE
Back button is not there

### ISSUE THREAD

**Issue by mysteriously** [Apple-Music-Electron/Apple-Music-Electron#148]
Hello guys,

I updated to latest Windows build and  don't see it :P Tried to delete preference file but no change

_Originally posted by @mysteriously in https://github.com/Apple-Music-Electron/Apple-Music-Electron/issues/124#issuecomment-887105857_

**Comment by cryptofyre** [comment]
It is available in the Advanced Options menu. Its still a WIP so we put it there for now.

**Comment by mysteriously** [comment]
Yes, I see the option, but it does not show up for me on Windows 10. Config file says it is enabled

**Comment by coredev-uk** [comment]
The back button only appears when you can go back, try clicking on a playlist

**Comment by mysteriously** [comment]
I did try and it don't appear. x64

**Comment by Larkify** [comment]
Its still a WIP.... don't expect it to work ig.

**Comment by nomynameisjoel** [comment]
Back button appears in dark mode but not in light mode

**Comment by coredev-uk** [comment]
Currently, because of the location that the back button is in and because it's only got a light variant, you can only view the back button if you are using macOS App Emulation and are using dark mode. A fix for this will be made soon.
