### ISSUE TITLE
JavaScript Error when playing musics

### ISSUE THREAD

**Issue by Lvieira21** [Apple-Music-Electron/Apple-Music-Electron#149]
Just updated from 2.4.0 beta4 to official 2.4.0, and I keep getting this error when trying to play a music. 
![JS error](https://user-images.githubusercontent.com/14310311/127147660-da454b8f-dffa-46a7-8f3b-25c754d479ba.png)
The error keeps poping up 5 times in a roll, and when it finishes, the music starts playing.

I'm on Windows 10 64bits (20H2)

**Comment by coredev-uk** [comment]
Go to %appdata%/Apple Music and delete preferences.json then relaunch

**Comment by Lvieira21** [comment]
That fixed it, it showed up once more when trying to listen to a radio, but after dismissing it, the radio started playing and it is not showing this message anymore.

Thanks
