### ISSUE TITLE
Unable to move app window

### ISSUE THREAD

**Issue by mysteriously** [Apple-Music-Electron/Apple-Music-Electron#150]
Hello,

This is new bug as everything worked in 2.30 beta 4. Once you forceDisableWindowFrame and restart the app, it is not possible to move the app window anymore. You can still resize it though. Windows 10 x64

**Comment by child-duckling** [comment]
Are you able to drag it on the top left (above or around the search bar)?

**Comment by mysteriously** [comment]
No, I am not

**Comment by coredev-uk** [comment]
Force disable window frame is primarily for Linux users who use a tiled window manager. If your aim is to either have the default windows frame, just disable macOS emulation and if you want the macOS frame then just enable the emulation. forceDisableWindowFrame just disables any kind of default frame. Make sure you know what you're doing when messing with the advanced settings.

**Comment by mysteriously** [comment]
Ok, I thought it is a bug as it worked fine in previous version

**Comment by coredev-uk** [comment]
> Ok, I thought it is a bug as it worked fine in previous version

In my reply I was saying it works as intended, in previous versions it did work as disabling the macOS window frame, but now as it's placed in the advanced category it no longer does that. It just force disables it so no frame is there, meaning no window controls.
