### ISSUE TITLE
[ ] Close button should minimize app

### ISSUE THREAD

**Issue by mysteriously** [Apple-Music-Electron/Apple-Music-Electron#152]
Hi,

When 'close button should minimize app' option is disabled, the app is not closed anyway. It minimizes to taskbar instead. Windows 10 x64, latest stable. This bug was also present in 2.40 beta 4

**Comment by child-duckling** [comment]
Did you relaunch the app after changing the setting?

**Comment by mysteriously** [comment]
Sure
