### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by Larkify** [Apple-Music-Electron/Apple-Music-Electron#153]
When clicking the settings from the menu, It asks me to login (I already have upon entering the app) and after signing in, it continues to ask me to sign in. Like when I click the sing in button after inputting details, it just goes back to the start.

**Comment by mysteriously** [comment]
Setting are for Apple account settings not for the app settings. IMO it should be removed completely

**Comment by coredev-uk** [comment]
We kept the normal Settings option to allow users to still access the full functionality of the Apple Music webapp. To make it clear, App Settings is the option to open the Settings GUI.
