### ISSUE TITLE
Apple Music is not available in your country or region.

### ISSUE THREAD

**Issue by Fa-ke** [Apple-Music-Electron/Apple-Music-Electron#154]
![image_2021-07-29_230352](https://user-images.githubusercontent.com/68967460/127593549-31482b37-9d59-483b-a9ca-ce54831ab5e6.png)

As title says
Try'd to log in and it gave me this error I live in the US any help/fixes? 
No VPN is on Btw

**Comment by child-duckling** [comment]
Ctrl + Alt + S -> [x] Auth Mode -> Apply -> Relaunch -> Login -> Ctrl + Alt + S -> [] Auth Mode -> Relaunch

**Comment by child-duckling** [comment]
please refer to #155
