### ISSUE TITLE
"Apple Music Not Available In Country or Reigon"

### ISSUE THREAD

**Issue by child-duckling** [Apple-Music-Electron/Apple-Music-Electron#155]
Please follow the instructions [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting#authentication-issues) to fix this issue.

Any issues that are opened relating to this exact problem will be closed and redirected here.

**Comment by MohammedAbidNafi** [comment]
Still this issues presists
