### ISSUE TITLE
Write EPIPE error when compiling

### ISSUE THREAD

**Issue by jairaume** [Apple-Music-Electron/Apple-Music-Electron#156]
Hello,
Quick question because i wanted to try and compile the code withe the provided on-liner powershell command but it fails right at the end of the _yarn dist_ with **"Error : write EPIPE"**. It still compiles into the dist folder but when launching the app i get some module missing error so i guess it's caused by the EPIPE error during the build.
I don't know if I've done something wrong or if everyboddy else gets this error but i figured i'd ask anyways.
thank you :)

**Comment by child-duckling** [comment]
@coredev-uk this is my fault. will self assign

**Comment by child-duckling** [comment]
@jairaume try doing `cd Apple-Music-Electron; yarn install` but wait 'till it finishes then do `yarn dist`.
What is happening is that the `postinstall` command isn't running until AFTER the dist command. It needs to run before.
Will adjust wiki one-liner.

**Comment by jairaume** [comment]
Thank you for your response but, i still get the same error
While running each command individually i noticed at the very end of the `yarn install` a `YN0000: Failed with errores in 1m 7s`.
Could that be the problem because on another pc i can compile everything without any errors...

**Comment by coredev-uk** [comment]
Have you just tried deleting the entire thing and cloning it again then installing again just using npm this time. Clone it, `npm i` then `npm run dist`. If that doesn't work, just try doing `yarn start` / `npm run start` and see if that opens the application. There's not reason why the packages wouldn't install with yarn install or npm i

**Comment by jairaume** [comment]
Thank you very much, i didn't think about trying it with npm but that was the issue because now it works perfectly on both of my machines.
Thank you for your patience and good luck on this amazing project !

**Comment by coredev-uk** [comment]
Glad to hear it and thanks.
