### ISSUE TITLE
Clicking Sign In Never Loads User/Pass input

### ISSUE THREAD

**Issue by stayrusty** [Apple-Music-Electron/Apple-Music-Electron#157]
Having an issue getting a login screen, I've tried with authMode set to true and false, same result. There also doesn't seem to be anything written to the log when Sign In is pressed. Attached the log. Windows 10, app version 2.4.0

authMode: false
![image](https://user-images.githubusercontent.com/8736049/127722839-e5723513-4e5e-4b5a-8b0e-71115f0e9486.png)

authMode: true
![image](https://user-images.githubusercontent.com/8736049/127722853-1e65b7d9-a066-4ba6-919f-8c0a021d1dda.png)

[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/6910396/main.log)

**Comment by cryptofyre** [comment]
Apple might be doing background fixes. Try again in a few minutes or something.

**Comment by stayrusty** [comment]
I fixed it by deleting the ~/AppData/Roaming/Apple Music directory, not sure what was corrupt there. Thanks.
