### ISSUE TITLE
[BUG] Loads as Spanish, won't allow me to login to account, now app won't even launch

### ISSUE THREAD

**Issue by jbwharris** [Apple-Music-Electron/Apple-Music-Electron#160]
**Describe the bug**
On first run it loaded with the default language as Spanish, then when I attempted to log into my account I was given an error about AM not being available in my country(Canada most definitely is). I shut down the app and attempted to see if restarting would work. On second attempt to open I received this JS error.   

    Uncaught Exception:
    Error: EACCES: permission denied, lstat '/Users/username/Library/Caches/Apple Music/Themes/README.md'
    at lstatSync (fs.js:1077:3)
    at Object.e.lstatSync (electron/js2c/asar_bundle.js:5:3528)
    at Object.lstatSync (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:311:34)
    at statFunc (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/util/stat.js:24:20)
    at getStatsSync (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/util/stat.js:27:16)
    at Object.checkPathsSync (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/util/stat.js:67:33)
    at copyDirItem (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy-sync/copy-sync.js:121:29)
    at /Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:39
    at Array.forEach (<anonymous>)
    at copyDir (/Applications/Apple Music.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy-sync/copy-sync.js:115:23)

I deleted the app, reinstalled and deleted the cache in /Library/Caches/Apple Music and was able to replicate the same thing happening, couldn't login, then close the app and then am unable to open it a second time. I attempted to enable authMode with Command + Option + S, but I don't see any confirmation of anything happening or changing in the app. Since I can't login, I can't do the profile step outlined in the Troubleshooting FAQ. 

**Screenshots**
![Screen Shot 2021-08-03 at 11 41 06 AM](https://user-images.githubusercontent.com/2962327/128045370-32f30577-3a19-45e1-a75a-a14eef1641ed.png)
![Not available](https://user-images.githubusercontent.com/2962327/128047256-fbca5a44-9ee8-4ac2-8e59-a84188c7775c.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 11.15.1

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting)?**
Yes

**Comment by coredev-uk** [comment]
Regarding your first issue, we are aware of this and it has been fixed for the next release. With the 'Apple Music is not available in your country or region' I suggest you turn on authMode then restart the application using Activity Monitor.

**Comment by tecandrew** [comment]
How to turn on `authMode` on Windows? I'm seeing this as well.

**Comment by jbwharris** [comment]
@coredev-uk how do I know it's turned on? Is there some indication it's active?

**Comment by coredev-uk** [comment]
> How to turn on `authMode` on Windows? I'm seeing this as well.

CTRL + ALT + S and just turn in authMode in there. Then restart the application

**Comment by coredev-uk** [comment]
> @coredev-uk how do I know it's turned on? Is there some indication it's active?

Currently, the only way that you can really tell is if certain content is missing from the site. authMode appends the command line of the application to disable CORS (Cross-origin resource sharing) which prevents Apple's site from being able to use images/assets from other origins. Usually, the main indication would be this. If you have devtools on you should also see web security warnings in the console if you enable authMode
