### ISSUE TITLE
[BUG] Blur removes text from sidebar

### ISSUE THREAD

**Issue by tecandrew** [Apple-Music-Electron/Apple-Music-Electron#161]
**Describe the bug**
Text is missing from the sidebar, except for the playlists.

**To Reproduce**
1. Download App
2. Login through using `authMode`
3. Use app

**Expected behavior**
Text to be on sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/21319730/128079359-722d20de-45c9-4953-bcd0-52cee31f32f5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Application Version: v2.4.0 (no indicator anywhere in application that shows this)

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
Yes

**Comment by tecandrew** [comment]
Unrelated, but Apple logo is also not centered in the Music player when nothing is playing.

![image](https://user-images.githubusercontent.com/21319730/128079997-90ad356c-5c46-4044-a0dd-7d67a028b1f5.png)

**Comment by coredev-uk** [comment]
Make sure you have disabled authMode once logged in.

**Comment by tecandrew** [comment]
yup, that fixed it. didn't realize I had to toggle it off afterwards
