### ISSUE TITLE
The interface buttons don't work. [BUG] 

### ISSUE THREAD

**Issue by urajsingh** [Apple-Music-Electron/Apple-Music-Electron#162]
The windows buttons (window minimize and close ones) do not work anymore for me. Didn't do anything.

I tried everything, including reinstalling. The buttons don't work anymore but everything else works. I just can't exit, maximize or exit the window with buttons.

Expected behavior:

Desktop:
 - OS: Windows 10 x64
 - Application Version: 2.4.0

Log File:

**Comment by cryptofyre** [comment]
Fixed in 2.4.1 coming out shortly.

**Comment by urajsingh** [comment]
> 
> 
> Fixed in 2.4.1 coming out shortly.

Oh okay. Thanks. :)
