### ISSUE TITLE
No music playback on compiled version

### ISSUE THREAD

**Issue by jairaume** [Apple-Music-Electron/Apple-Music-Electron#164]
I can't play music when i `npm run start` the application (freshly cloned)
When choosing a song it displays itself with its title, artwork, etc. but the progress bar is "loading".
(I'm trying to implement dynamic colors based on the artwork but i unfortunately can't test my code if I can't play a song)

**Comment by mysteriously** [comment]
It happened for me as well. Close app from tray and delete %appdata%\Apple Music\Preferences and Preferences.json

**Comment by coredev-uk** [comment]
`npm run start` is only supposed to be used for development purposes not for playing music. In that state widevine is not authorized, only for some reason on Linux, it is. I suggest you don't use `npm run start` or `yarn start` to run the application and compile it to play music.



> It happened for me as well. Close app from tray and delete %appdata%\Apple Music\Preferences and Preferences.json
> 
> Also language selection does not enforce the language anymore. It shows up in Polish even if config file says en

Could you show me your .log file please, open a ticket on the discord and post your log there.
