### ISSUE TITLE
[BUG] cloud music library songs dont have cover art

### ISSUE THREAD

**Issue by peepee** [Apple-Music-Electron/Apple-Music-Electron#169]
**Describe the bug**
songs uploaded to the cloud music library do not show their cover art on apple music electron, only showing the default music note icon. this does not happen with apple music songs

**To Reproduce**
1. upload a song to cloud music library using apple music/itunes on macos (or itunes on windows)
2. add cover art to the song
3. play the song on apple music electron

**Expected behavior**
on the left of the player, the cover art associated with the song should show, just like apple music songs

**Screenshots**
this song is an apple music song, so its cover art appears in the player just fine
![image](https://user-images.githubusercontent.com/49787675/128728727-b7a1abb8-82d6-4e22-9545-576f47c6b2c9.png)
this song is a song i uploaded to cloud music library on my mac, and its cover art only appears when browsing, not in the player
![image](https://user-images.githubusercontent.com/49787675/128728771-5ae2e1bf-decd-4d6d-bdc7-f03c47b35054.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Application Version: 2.4

**Log File**
[(probably irrelevant)](https://gist.github.com/peepee/08de042e58e9e05a2c95ac9caf84311e)

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
yes

**Comment by cryptofyre** [comment]
You might wanna report this to Apple as they handle all the Cloud based stuff and we have no control over the data they send us.

[Report here.](https://www.apple.com/feedback/apple-music.html)

**Comment by peepee** [comment]
> You might wanna report this to Apple as they handle all the Cloud based stuff and we have no control over the data they send us.
> 
> [Report here.](https://www.apple.com/feedback/apple-music.html)

oh

**Comment by peepee** [comment]
github flipped out and i accidentally closed the issue. apologies.

**Comment by cryptofyre** [comment]
Closing this issue as its something we really can’t do anything about.
