### ISSUE TITLE
Sugest

### ISSUE THREAD

**Issue by F3R96** [Apple-Music-Electron/Apple-Music-Electron#170]
Hi there! 

I'm new to this app. I was wondering, is there anyway to play the local music? The one on my computer I mean.

Also, the app says there are notifications on song change, but none has appear so far...

Using windows 10 64 bit. The taskbar is hiden. This app looks so good! Superb job

![imagen](https://user-images.githubusercontent.com/78397863/128916000-9796d043-e22a-4433-a514-08bfd27dddec.png)

**Comment by child-duckling** [comment]
The only way you could TECHNICALLY do it, is to import the music into the iTunes and have "Sync Library" switched on. This syncs your library (Streamed, Downloaded, and locally imported) with all devices including the web app
