### ISSUE TITLE
Double Media Indicator (Elementary OS)

### ISSUE THREAD

**Issue by tofutech** [Apple-Music-Electron/Apple-Music-Electron#171]
**Describe the bug**
When using on Elementary OS, it shows double Now Playing indicators in the Sound Menu. I don't know if this is an issue with this app or with Elementary itself but the deprecated Electron wrapper from 17hoebr (https://github.com/17hoehbr/apple-music-electron) did not have this issue.

**To Reproduce**
1. Open app.
2. Play music.
3. Open sound menu.

**Expected behavior**
Single Now Playing Indicator

 - OS: Elementary OS 6.0 
 - Application Version  2.4.0

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
Yes
![Screenshot from 2021-08-10 23-39-13](https://user-images.githubusercontent.com/81934761/128966388-1e0cc9ae-6c58-4682-9f69-7c7fda2d631a.png)

**Comment by coredev-uk** [comment]
The reason why 2 appear is that both Mpris and the Electron window are creating media instances, 17hoebr's build does not include support for mpris.

**Comment by tofutech** [comment]
Ahh, gotcha. Is there anything that can be done to bypass this/workaround?

**Comment by coredev-uk** [comment]
I can add a configuration option for disabling mpris, this will make it so there's only 1 audio instance being generated from the application, however, the album image and certain details will not be visible.

**Comment by coredev-uk** [comment]
73ddb8f has the configuration option.

**Comment by child-duckling** [comment]
it would be better if only mpris is enabled, not the other way around. For  *nix at least

**Comment by coredev-uk** [comment]
I would like that but I don't know how to remove/disable the chromium audio instance, if you have any idea how that'd be great.

**Comment by tofutech** [comment]
I'm entirely new to Electron, honestly have no clue how it works, but apparently there's a chromium flag that disables Chromium from hijacking mpris, maybe this thread couple help somehow? https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/10

**Comment by child-duckling** [comment]
Nice

@coredev-uk - the flag is `--disable-features=MediaSessionService`

**Comment by tofutech** [comment]
Kinda wild that I was able to spitball that. Should I just add that flag to my .desktop file then? Launched from terminal and works like a charm.
![Screenshot from 2021-08-11 23-57-52](https://user-images.githubusercontent.com/81934761/129136238-d066f61c-222c-4f1f-91c4-04b5df74ef9a.png)

**Comment by tofutech** [comment]
Update: added the flag to the end of the command section of the .desktop file and works great.

**Comment by coredev-uk** [comment]
> --disable-features=MediaSessionService

Thanks, I didnt even see this
