### ISSUE TITLE
[BUG] Can't toggle between Apple Music and my library within search

### ISSUE THREAD

**Issue by Nosh118** [Apple-Music-Electron/Apple-Music-Electron#179]
**Describe the bug**
When the back button is being added to the search page, it prevents the user from toggling between searching "Apple Music" or "Your Library". 

**To Reproduce**
1. Go to the search bar
2. Type something in and press enter
3. Try to toggle to search within your library

**Expected behavior**
Being able to search just my library

**Screenshots**
![image](https://user-images.githubusercontent.com/67752804/129711841-481868d0-1d79-4809-a6e9-94b7ef16cd58.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux/Mac/Windows] Windows
 - Application Version [e.g. 2.4.0] 2.5.0 beta

**Log File**
Check your log file for any errors or the last message to be sent and post them here.

**Additional context**

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
No

**Comment by cryptofyre** [comment]
I'll look into this.
