### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ressonix** [Apple-Music-Electron/Apple-Music-Electron#184]
Issue: When launching the application on Windows, an error dialog box appears and says the following:

![image](https://user-images.githubusercontent.com/60057409/130242024-8a6a9cd6-89d6-42ea-9066-ff51c628475b.png)

The error mentions the UNIX command chmod, so maybe that's where the issue lies?

Affects Version: 2.4.1
OS: Windows 10

**Comment by alombi** [comment]
Did you solved this issue? I have the same problem (on Mac) and I don't know how to solve it

**Comment by cryptofyre** [comment]
2.4.X releases are currently experiencing that bug. Apologies for the inconvenience this has been fixed in 2.5.0 and will be releasing publicly soon.

**Comment by alombi** [comment]
Thank you!
