### ISSUE TITLE
Apple Music is not available in your country or region.[BUG] 

### ISSUE THREAD

**Issue by drumerpunk1** [Apple-Music-Electron/Apple-Music-Electron#185]
**Describe the bug**
I log in and it says Apple Music is not available in your country or region. I'm in the USA so i can't see how this is a problem.

**To Reproduce**
1. Go to log in

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux/Mac/Windows]
 - Application Version [e.g. 2.4.0]

**Log File**
Check your log file for any errors or the last message to be sent and post them here.

**Additional context**

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
Yes/No

**Comment by coredev-uk** [comment]
Please provide the rest of the information that the template requests, more specifically what version are you on?

**Comment by cadegorawrz** [comment]
I'm getting this on 2.4.1 on Windows 10 using the EXE and Winget installation!

**Comment by coredev-uk** [comment]
I suggest you upgrade to v2.5.0, which can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/releases/tag/v2.5.0). On this version, the issue is fixed.

**Comment by cadegorawrz** [comment]
That fixed it! Thank you!

**Comment by coredev-uk** [comment]
Glad to hear it, if you or anyone else experience any UI issues (as we have had reports of css not being loaded) with elements disappearing follow the [clean installation guide](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting#clean-installation)
