### ISSUE TITLE
[BUG] Javascript error while launching

### ISSUE THREAD

**Issue by shanuflash** [Apple-Music-Electron/Apple-Music-Electron#192]
First time install the app, I get this when I launch the app
OS: Windows 11, I have iTunes installed if it has something to do with it
Version: 2.4.1 latest
I also did a clean install following the wiki, still no luck :(

![image](https://user-images.githubusercontent.com/39374797/130824771-4f029adb-bc00-4669-acd1-ac9e351a8b79.png)

Logs: https://katb.in/kat10021

**Comment by shanuflash** [comment]
Update: I just installed 2.5.0 [BETA], it seems working, I think its because of windows 11

**Comment by coredev-uk** [comment]
Its not windows, it was a bug with 2.4.1
