### ISSUE TITLE
[BUG] Stop music and cannot play again for a while

### ISSUE THREAD

**Issue by thaithantho** [Apple-Music-Electron/Apple-Music-Electron#199]
I have the same issue every day, I listen normally and then stop to play games. After approximately 30 minutes, I click play again and it won't work. Does anyone know how to fix it? I'm using the latest version.

**Comment by coredev-uk** [comment]
Try closing the application then reopening it when you stop playing games. If there is an error that is shown, that'd be great if you could post it.

**Comment by coredev-uk** [comment]
No response from the user in a month, closing the issue.
