### ISSUE TITLE
[BUG] Listen Now tab displays nothing

### ISSUE THREAD

**Issue by SaukiFarisy** [Apple-Music-Electron/Apple-Music-Electron#200]
I have an issue today. When I click on the listen now tab it displays nothing. But when I click on the other tabs is normal. And my playlist are disappear. I use acrylic theme and acrylic transparency. I attach the screenshot down below.
![G5IWuKitE2](https://user-images.githubusercontent.com/71185577/131480488-ecb965e4-a66d-42f7-b28a-87f93a995665.png)

**Comment by coredev-uk** [comment]
Performing a [clean installation](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting#clean-installation) should resolve this.
