### ISSUE TITLE
[Enhancement] Option to switch streaming quality

### ISSUE THREAD

**Issue by Carlgo11** [Apple-Music-Electron/Apple-Music-Electron#205]
**Is your feature request related to a problem? Please describe.**
It would be great with an option to enable higher quality streaming. Perhaps leveraging something like [this](https://www.reddit.com/r/AppleMusic/comments/dit7n1/apple_music_web_player_audio_quality_question/fl0fewd/?utm_source=reddit&utm_medium=web2x&context=3).
I'm guessing it may be possible by injecting JavaScript into each window that replaces the requested streaming URL with a high res version `.rphq`-file version. 

**Describe the solution you'd like**
Option in the preferences menu to use higher-res audio streaming.

**Comment by cryptofyre** [comment]
Already present as of 2.5.1
