### ISSUE TITLE
[BUG] Failed to install WIDEVINE components - Windows 10

### ISSUE THREAD

**Issue by chigoch** [Apple-Music-Electron/Apple-Music-Electron#206]
Trying to install on windows 10. Getting this error. 

The version is 2.5.

![20210903234029](https://user-images.githubusercontent.com/90056447/132032513-10da9b58-76ba-4c1a-98e8-8ef2049bc098.jpg)

**Comment by coredev-uk** [comment]
Try completing a [clean installation](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting#clean-installation)

**Comment by chigoch** [comment]
![20210903235552](https://user-images.githubusercontent.com/90056447/132034116-db2238f2-de1e-42fd-812c-b4223ffc6e73.jpg)

**Comment by coredev-uk** [comment]
So you did follow the guide?

**Comment by chigoch** [comment]
> So you did follow the guide?
Yes,I did.

**Comment by JackesRrmhX** [comment]
I have same issue too. 
![image](https://user-images.githubusercontent.com/48159667/132485061-6366d77b-7f10-44b3-be84-7e9787f1e497.png)

**Comment by JackesRrmhX** [comment]
> I have same issue too.
> ![image](https://user-images.githubusercontent.com/48159667/132485061-6366d77b-7f10-44b3-be84-7e9787f1e497.png)

I think the problem is chinese network

**Comment by coredev-uk** [comment]
Try using the Apple Music website, for the time being, I'm not sure of any other methods.

**Comment by child-duckling** [comment]
Closing for now
