### ISSUE TITLE
[Enhancement] Visualizer

### ISSUE THREAD

**Issue by coredev-uk** [Apple-Music-Electron/Apple-Music-Electron#210]
Suggested by @booploops#7139 in Discord.

https://github.com/booploops/my-userscripts/blob/master/AM-Extension%20Scratchpad.js
https://www.youtube.com/watch?v=mtMd5sHu0tY

**Comment by child-duckling** [comment]
You can do this with three.js

**Comment by coredev-uk** [comment]
After looking into the method that the user provided, the resource usage and space that would be used up would not be viable as an addition to the app.
