### ISSUE TITLE
[Enhancement] Preferences page integrated with the site

### ISSUE THREAD

**Issue by coredev-uk** [Apple-Music-Electron/Apple-Music-Electron#211]
The easiest way to do this would probably be directing users to account settings and set the inner HTML of the box div.

**Comment by coredev-uk** [comment]
#223 to be implemented with this.

**Comment by child-duckling** [comment]
I got the lastfm side. 
Thinking just a basic URI
```
if (String(param).includes('auth')) {
            // [URI]://auth/?token=[32 Char token]
            app.preferences.value('general.lastfmAuthKey') = String(param).split('token=')[1]
}
```

**Comment by child-duckling** [comment]
https://www.last.fm/api/auth?api_key=[apiKey]&cb=ame://auth` -> 
`Allow Access` ->
`ame://auth/?token=[32 Char token]` -> 
`app.preferences.value('general.lastfmAuthKey', String(param).split('token=')[1])`

**Comment by child-duckling** [comment]
[ab1d60a](https://github.com/Apple-Music-Electron/Apple-Music-Electron/commit/ab1d60a975bfcf5c731d869c32205420a54897ea) -`Store.set('lastfm.token') = String(param).split('token=')[1])`

**Comment by coredev-uk** [comment]
Done.

**Comment by child-duckling** [comment]
> I got the lastfm side. 
> 
> Thinking just a basic URI
> 
> ```
> 
> if (String(param).includes('auth')) {
> 
>             // [URI]://auth/?token=[32 Char token]
> 
>             app.preferences.value('general.lastfmAuthKey') = String(param).split('token=')[1]
> 
> }
> 
> ```

will do today
