### ISSUE TITLE
[Enhancement] Option to use normal Win32 title bar and window options instead

### ISSUE THREAD

**Issue by ctaetcsh** [Apple-Music-Electron/Apple-Music-Electron#212]
Not sure if this would be possible with Electron's whole thing but an option to use the normal Windows title bar would be appriciated cause right now the right-aligned window options make the general UI kind of wonky.
![image](https://user-images.githubusercontent.com/48845980/132978208-3284a505-7d2c-4199-bcf8-361bf4f4a29b.png)

**Comment by coredev-uk** [comment]
Just disable macOS emulation in preferences and that'll enable the windows titlebar.

**Comment by ctaetcsh** [comment]
Thanks, that worked. However the option is quite counter intuitive as its not made clear that the "Select One" option is the disabled option. 
![image](https://user-images.githubusercontent.com/48845980/133004775-7af13deb-dea1-4b6b-a86d-0d9e4345559c.png)

**Comment by coredev-uk** [comment]
Well, I aim to make a Windows frame for that application, and clean up the menu with the options of Frame being dropdown for MacOS or normal.
