### ISSUE TITLE
[Enhancement] Allowing users to change application name for Discord RPC

### ISSUE THREAD

**Issue by pim9704** [Apple-Music-Electron/Apple-Music-Electron#213]
It would be really nice if we could create a custom name for the application!

Now it says "Apple Music Electron", and I would really like to be able to change it to just "Apple Music". I think it would look a lot cleaner, since now it's cut off on desktop, ("Playing **Apple Music El**...."). 

It's just a small thing, I know :). But, it would be a nice QoL addition to this project, I think.

Would this kind of feature be possible, or is there limitations on Discord's end for Rich Presence titles? I couldn't find any information online explicitly confirming that the app title cannot be updated by the end-user. If this is the case however, I apologize and you can consider my request redacted.

**Comment by coredev-uk** [comment]
Sorted, it will be available in the next release.
