### ISSUE TITLE
[BUG] Login not working correctly

### ISSUE THREAD

**Issue by tofutech** [Apple-Music-Electron/Apple-Music-Electron#214]
**Describe the bug**
App will not correctly login, or recognize login state on restart. When logged in, the app acts as if I am not, and does not show me any user data (playlists, albums, songs, etc.)

**To Reproduce**
1. Open app.
2. Log in.

**Expected behavior**
Login to work and stay logged in, and for my user data to show correctly.

**Screenshots**
![Screenshot from 2021-09-12 11-51-19](https://user-images.githubusercontent.com/81934761/132994417-18de59ef-874e-495a-9c89-ef6deb5583e7.png)
![Screenshot from 2021-09-12 11-50-20](https://user-images.githubusercontent.com/81934761/132994418-598a2be7-6d3b-4619-91bd-e47e8544648a.png)

**Desktop**
 - OS: Elementary OS Odin
 - Application Version 2.5.0

**Comment by coredev-uk** [comment]
Do a [clean installation](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting#clean-installation), make sure you're launching the application through a compiled state (I.e. no using the start command) and if that doesn't work, try switching region, then restart, then logging in then switching back and restarting.

**Comment by tofutech** [comment]
Tried all of the above, same issue.

**Comment by coredev-uk** [comment]
You using the appimage?

**Comment by tofutech** [comment]
Currently using the .deb

**Comment by coredev-uk** [comment]
Do you have a package manager?

**Comment by tofutech** [comment]
Not currently,just downloaded the .deb and installed from terminal.

**Comment by coredev-uk** [comment]
The best I can recommend is to try compiling yourself or swap off the beta (Under advanced in the Preferences menu) and logging in that way.

**Comment by tofutech** [comment]
It might be an issue with the OS I was using, I'm not entirely sure. I do know that I am on Manjaro on my main PC, installed from the AUR with no issue so not sure what the problem was.

**Comment by coredev-uk** [comment]
I'll keep an eye out for any other issues with the application on Elementary OS Odin. Any further issues feel free to open another issue.
