### ISSUE TITLE
[BUG] Themes won't apply

### ISSUE THREAD

**Issue by SubZeroNexii** [Apple-Music-Electron/Apple-Music-Electron#216]
**Describe the bug**
Setting any theme from the preferences window will not apply the theme after a restart.

**To Reproduce**
1. Go to the Preferences window
2. Set any available theme
3. Restart the app
4. The theme will still be the default one and the preferences window will also show the "default" theme option.

**Desktop (please complete the following information):**
 - OS: Windows 11 Dev build 22458.1000 and Windows 10 21H1
 - Application Version v2.5.0-nightly.1

**Screenshots**
![2021-09-18_12-37-14](https://user-images.githubusercontent.com/11245286/133884452-d960865c-a6dc-4a20-9db7-57ffae6e6863.gif)

**Comment by SubZeroNexii** [comment]
Here's the logfile: [https://pastebin.com/6g0SwYjj](url)

Apparently the problem is that it can't clone the themes git

**Comment by coredev-uk** [comment]
Try and manually clone this [repo](https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes) into %appdata%/AppleMusic/themes

**Comment by SubZeroNexii** [comment]
> 
> 
> Try and manually clone this [repo](https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes) into `%appdata%/AppleMusic/themes`

Thanks. This did "fix" it. Was expecting it to, really. I guess the bigger problem is that the app can't clone the repo for some reason.

**Comment by coredev-uk** [comment]
Since the nightly build we switched modules for cloning the repo, so hopefully next time it shouldn't happen.
