### ISSUE TITLE
[BUG] adamId: null not found

### ISSUE THREAD

**Issue by JeazyEasy** [Apple-Music-Electron/Apple-Music-Electron#219]
So when I'm starting Apple Music it works for a short amount of time until the music suddenly stops. I can't resume it and I can't skip to the next song either. I just get the "adamId: null not found" error and am forced to close apple music and start it again.

I tried a clean install, didnt do anything. Maybe someone knows a workaround. Thanks in advance.

**Comment by coredev-uk** [comment]
This seems to be a common issue for Apple's site, I don't believe there is much we can do as it's the website itself that causes the issue. The best thing I can recommend is make a feedback report for Apple Music found [here](https://www.apple.com/feedback/apple-music.html).
