### ISSUE TITLE
[Bug] Non Clean Music Automatically

### ISSUE THREAD

**Issue by whippingdot** [Apple-Music-Electron/Apple-Music-Electron#230]
**Describe the bug**
I don't know exactly if this is a bug, but I think it is. So basically I am a clean user, meaning I have the clean filter on in Apple Music. On Apple Music on my iPad all the explicit songs everywhere are replaced with the clean songs by default, and so if I search 16 by Baby Keem or look the top 100 Apple Music Global songs, it would automatically show all the clean versions. I also used to use apple music web on my windows machine and the same would happen. But now on your electron app everything is shown its explicit version and because of my settings I can't play anything. In Apple Music made playlists I have to go the album and look for the clean version of the song and play it, while in just normal albums I have to find the clean version and play it. Please fix this and make it so your app also automatically shows only the clean versions of songs instead of the explicit if the clean filter is on. I don't even know how you changed it and made that not work but 🤷 

**To Reproduce**
1. Go to your settings and add the song restrictions to clean only
2. Go to Browse and Global Top 100
3. Watch as all the explicit versions of songs show up and you can't play anything except the songs which have no explicit version

**Expected behavior**
All the songs with clean versions showing up as playable and when you press play the clean version plays.

**Screenshots**
Apple music website:
![image](https://user-images.githubusercontent.com/64354499/135419587-7a357be6-26b0-4de8-a928-782efae99fc9.png)

Apple music electron app:
![image](https://user-images.githubusercontent.com/64354499/135419696-53cc2cf1-6594-4104-ba96-e22a73658270.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Application Version [Couldn't find it but a very recent version for sure (I installed nightly and this was installed 3 days ago or something)]

**Log File**
Don't know where it is

**Comment by whippingdot** [comment]
wait also the album icons are different I just noticed...

**Comment by coredev-uk** [comment]
Try and open your settings menu and go to the advanced tab and then scroll down and uncheck useBetaSite then restart. If you want to go to [here](https://beta.music.apple.com) and try, it’ll probably show a bug with Apples beta site. Using the main site will limit you in terms of features, but should give you the filter.

**Comment by whippingdot** [comment]
Wait everything works now. I don't know what happened
