### ISSUE TITLE
[Enhancement] Dark / Light mode based on the system theme

### ISSUE THREAD

**Issue by Donnnno** [Apple-Music-Electron/Apple-Music-Electron#234]
**Describe the solution you'd like**
Many apps (for windows) support system based theming. I think that's really neat :^) 
Could be a nice thing to have.

**Is your feature request related to a problem? Please describe.**
I like light themes at day, but dark themes are better at night

**Additional context**
Idk if it's possible because AME has to restart after changing theme's right now.

**Comment by coredev-uk** [comment]
Currently the application does auto detect your system theme and configure the application to it. However, it does not automatically change. I'll look into implementing a method to set it to use default theme, should be easy.

**Comment by Donnnno** [comment]
Cool! Thanks :^)

**Comment by coredev-uk** [comment]
So I've managed to add support for it to auto change. However, if you decide to use transparency it will not auto-update as the transparency colour is only set when you launch the application, but the rest of the UI will update.

**Comment by Donnnno** [comment]
Wow, that was really fast!! Thank you :)
