### ISSUE TITLE
[Bug] Cannot Open App on MacBook Air (M1)

### ISSUE THREAD

**Issue by benmelling** [Apple-Music-Electron/Apple-Music-Electron#257]
**GIVEN** I am a MacBook Air (M1) user
**WHEN** I open the app
**THEN** The app should open as expected

Currently, when I open the installed app, it does not work. Please see screen recording attached: 

<img width="698" alt="Screenshot 2021-10-14 at 08 10 09" src="https://user-images.githubusercontent.com/39852644/137268904-fbcac9ea-2371-4659-8097-30924f35985b.png">

https://user-images.githubusercontent.com/39852644/137268764-b2feede8-c4de-40ff-a956-844d3e225de5.mov

**Comment by coredev-uk** [comment]
I have seen this issue on Mac, I think its an issue with the window handlers for the application. However, afaik M1 is not supported but the module (electron-builder) we use to build the application.
