### ISSUE TITLE
[BUG] macOS Emulation (Right) buttons are stretched vertically in the "Eleven" theme

### ISSUE THREAD

**Issue by idkwuu** [Apple-Music-Electron/Apple-Music-Electron#285]
**Describe the bug**
(title)

**To Reproduce**
1. Go to AME's Settings
2. Change the theme to "Eleven" or "Eleven (2.5.0)"
3. Change the application frame to "macOS Emulation (Right)"

**Expected behavior**
The macOS Emulation buttons should be displayed correctly

**Screenshots**

![macOS Emulation (Right) buttons](https://user-images.githubusercontent.com/42050584/138622724-df99287a-f54f-4018-af04-cab074cd8288.png)

**Environment Information**
 - OS: Linux
 - Application Version: built from git (commit: c13061b)

**Comment by coredev-uk** [comment]
Fixed in 646a06a
