### ISSUE TITLE
[BUG] Strange UI irregularities (no back button, themes not updating properly)

### ISSUE THREAD

**Issue by inalone** [Apple-Music-Electron/Apple-Music-Electron#290]
For some reason, I get strange UI irregularities such as themes not updating even when I restart the program (but some still change the layout, despite not changing the colours) and there always being a lack of a back button on any page I go on.
I have attached videos of both of these issues below (apologies for the choppiness of the second video).
https://www.youtube.com/watch?v=1Cw5ZPumkDQ
https://www.youtube.com/watch?v=nz5m19Ow8bw

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*:  Arch Linux
 - Application Version *(e.g. 2.5.0)*: master

**Log File**
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7412179/main.log)

**Comment by child-duckling** [comment]
seems solved
