### ISSUE TITLE
[BUG] Account settings is missing if you set the startup page to something specific.

### ISSUE THREAD

**Issue by variananora** [Apple-Music-Electron/Apple-Music-Electron#311]
**Describe the bug**
Account settings and Discord option are missing from the settings box if you set the startup page to:
- Recently Added
- Songs
- Albums
- Made for You

**To Reproduce**
1. Go to settings
2. Change your "Startup Page" to any of the above.
3. Restart the app

**Expected behavior**
It should shows you the "What is should be" (check the screenshot part).

**Screenshots**

Video: https://youtu.be/PawAO9bC1MQ

<details>
<summary>What it should be:</summary>

![image](https://user-images.githubusercontent.com/34732414/139188236-1f4fd925-61f8-4441-8dd5-54219f05e4e7.png)

</details>

<details>
<summary>Broken one:</summary>

![image](https://user-images.githubusercontent.com/34732414/139188255-3b05ae3f-d3a4-44cc-8a0f-2f1aa2c2d23e.png)

</details>

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 11 
 - Application Version *(e.g. 2.5.0)*: 3.0.0 (Commit: 7a82f0e826f20b1ad84353d8045d44f6c2390bc6)

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
https://haste.zneix.eu/okizohobul.sql

**Comment by variananora** [comment]
> As this seems to be an issue with scripts failing to execute and is not an issue that I can replicate, could you turn on verbose logging and post your `renderer.log` file (found in the same location as your log file) after experiencing the issue

Well it's kinda fixed (mitigated) by https://github.com/Apple-Music-Electron/Apple-Music-Electron/commit/d46fac30d2020e735385565e8545387fbdd986fa should I revert the version and do what you requested or just close this issue

**Comment by coredev-uk** [comment]
If it works fine with that, then maybe it was just an innerHTML issue. Go ahead and close this unless you need any other help.
