### ISSUE TITLE
[BUG] Back button misaligned & un-clickable on user profiles

### ISSUE THREAD

**Issue by SoNothingMC** [Apple-Music-Electron/Apple-Music-Electron#318]
**Describe the bug**
The back button is positioned under the area between the search bar and Listen Now, making it un-clickable.

**To Reproduce**
1. Get some friends (lol)
2. Go to a playlist/album where your friends appear (e.g. Friends Mix, albums that your friends listen to)
3. Click on their profile
4. Try to go back

**Expected behavior**
The back button is positioned like in the other sections of the app.

**Screenshots**

![The Apple Music interface with a green rectangle surrounding the misaligned back button](https://user-images.githubusercontent.com/32032824/139589292-8f8c6e3e-5371-46c6-98e2-177cef291b10.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 10 21H1 (19043.1320)
 - Application Version *(e.g. 2.5.0)*: Built from commit b0d54e13530dd0d199c95c6545019eb530a67885
 
**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

[main-redacted.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7449041/main-redacted.log)

**Comment by coredev-uk** [comment]
If you could compile on the latest release and test the back button that would be great.

**Comment by SoNothingMC** [comment]
It now works on my end. Thank you!

![The Apple Music interface, with the back button in its right position](https://user-images.githubusercontent.com/32032824/139681222-108b716f-a565-4092-97c0-eb7f32f45b88.png)

**Comment by coredev-uk** [comment]
Glad to hear it!
