### ISSUE TITLE
[BUG] Log file labels Windows 10 21H1 as Windows 11

### ISSUE THREAD

**Issue by SoNothingMC** [Apple-Music-Electron/Apple-Music-Electron#319]
**Describe the bug**
In main.log, the Release info shows Windows 11 on a Windows 10 build.

**To Reproduce**
1. Launch AME
2. Open main.log

**Expected behavior**
It shows up as Windows 10 instead of Windows 11.

**Screenshots**

![The log file of Apple Music Electron with the About Windows dialog on top of the editor window.](https://user-images.githubusercontent.com/32032824/139589741-a0404ffd-2766-4c7d-b17f-0c3c14bbd888.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 10 Pro 21H1 (19043.1320)
 - Application Version *(e.g. 2.5.0)*: Built from commit b0d54e13530dd0d199c95c6545019eb530a67885
 
**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

[main-redacted.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7449041/main-redacted.log)

**Comment by coredev-uk** [comment]
Resolved in f0e8dcd
