### ISSUE TITLE
[BUG] 登陆之后显示  您所在国家或地区不提供此项目   并且网页版本的也不能听了

### ISSUE THREAD

**Issue by BokaiLIAN** [Apple-Music-Electron/Apple-Music-Electron#324]

**Comment by vapormusic** [comment]
Please use English. If you have problems with the storefront,  you may try to clean the %appdata%/AppleMusic folder and install the 3.0.0 beta: https://github.com/Apple-Music-Electron/Apple-Music-Electron/actions/runs/1408081865 ( Download the artifacts file) .  Remember to select the correct region that you register the account in
