### ISSUE TITLE
[BUG] AM opens but won't generate any new windows

### ISSUE THREAD

**Issue by Piipperi** [Apple-Music-Electron/Apple-Music-Electron#340]
**Describe the bug**
I downloaded the dmg from releases for 2.5.0 (I did not have Apple Music Electron installed prior to this), I dragged it into my Applications folder. I opened it and trusted the app, and then nothing. The app is open and I can interact with the menu bar items, however, there are no windows generated. I tried opening the app via Terminal, I see other errors except `bootstrap_check_in():  (os/kern) unknown error code (44c)`, not sure is it related.

**Expected behavior**
I'd expect the app to at least bring up an error window

**Screenshots**
![Screen Shot 2021-11-05 at 18 20 12](https://user-images.githubusercontent.com/29174220/140544012-96d70bcd-6ddd-4cda-882e-37301e192a0e.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: macOS 12.0.1
 - Application Version *(e.g. 2.5.0)*:  2.5.0
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music
-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.
There was no log files, in fact no logs folder is even found.
![Screen Shot 2021-11-05 at 18 27 01](https://user-images.githubusercontent.com/29174220/140544848-c4769700-3841-4e18-92f2-0f1d6e58e13a.png)
d.

**Comment by child-duckling** [comment]
Is this on an Intel or M1 machine?

**Comment by coredev-uk** [comment]
Pretty sure this is all a result of 2.5.0 not being fully set up for support on macOS, a lot more tuning has been done since the release, and for the log file did you check both the directories listed in the wiki?

**Comment by Piipperi** [comment]
> Pretty sure this is all a result of 2.5.0 not being fully set up for support on macOS, a lot more tuning has been done since the release, and for the log file did you check both the directories listed in the wiki?

Yeah I tried checking both, no log files to be seen

**Comment by Piipperi** [comment]
> Is this on an Intel or M1 machine? 

Intel

**Comment by coredev-uk** [comment]
If you could try [compiling](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Compiling-on-Platforms#instructions) on your device from the master branch that would be great, as I'm sure this is fixed in the current build.

**Comment by Piipperi** [comment]
> If you could try [compiling](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Compiling-on-Platforms#instructions) on your device from the master branch that would be great, as I'm sure this is fixed in the current build.

I haven't been able to compile it from the guide provided on my Mac nor on my Windows machine. Both result in ```error Command failed with exit code 1.```
```info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```
when I try compiling. It happens after I do yarn dist.

**Comment by vapormusic** [comment]
> > If you could try [compiling](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Compiling-on-Platforms#instructions) on your device from the master branch that would be great, as I'm sure this is fixed in the current build.
> 
> I haven't been able to compile it from the guide provided on my Mac nor on my Windows machine. Both result in `error Command failed with exit code 1.` `info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.` when I try compiling. It happens after I do yarn dist.

It would be helpful if you provide us the full build log

**Comment by Piipperi** [comment]
> > > If you could try [compiling](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Compiling-on-Platforms#instructions) on your device from the master branch that would be great, as I'm sure this is fixed in the current build.
> > 
> > 
> > I haven't been able to compile it from the guide provided on my Mac nor on my Windows machine. Both result in `error Command failed with exit code 1.` `info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.` when I try compiling. It happens after I do yarn dist.
> 
> It would be helpful if you provide us the full build log

Is it [crash.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7506632/crash.log)?

**Comment by coredev-uk** [comment]
If you could just compile and then copy and paste the last 6 lines or so of the error. What you have provided is just the error code.

**Comment by Piipperi** [comment]
> If you could just compile and then copy and paste the last 6 lines or so of the error. What you have provided is just the error code.

I tried to compile again, now I'm getting a bunch of errors like this
```
    gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/Users/Piipperi/Apple-Music-Electron/node_modules/node-gyp/lib/configure.js:259:16)
    gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    gyp ERR! System Darwin 21.1.0
    gyp ERR! command "/usr/local/bin/node" "/Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig/node_modules/.bin/node-gyp" "rebuild"
    gyp ERR! cwd /Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig
    gyp ERR! node -v v17.0.1
    gyp ERR! node-gyp -v v8.4.0
    gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vapormusic** [comment]
> > If you could just compile and then copy and paste the last 6 lines or so of the error. What you have provided is just the error code.
> 
> 
> 
> I tried to compile again, now I'm getting a bunch of errors like this
> 
> ```
> 
>     gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
> 
>     gyp ERR! configure error 
> 
>     gyp ERR! stack Error: `gyp` failed with exit code: 1
> 
>     gyp ERR! stack     at ChildProcess.onCpExit (/Users/Piipperi/Apple-Music-Electron/node_modules/node-gyp/lib/configure.js:259:16)
> 
>     gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
> 
>     gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> 
>     gyp ERR! System Darwin 21.1.0
> 
>     gyp ERR! command "/usr/local/bin/node" "/Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig/node_modules/.bin/node-gyp" "rebuild"
> 
>     gyp ERR! cwd /Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig
> 
>     gyp ERR! node -v v17.0.1
> 
>     gyp ERR! node-gyp -v v8.4.0
> 
>     gyp ERR! not ok 
> 
> error Command failed with exit code 1.
> 
>     
> 
>                     command=/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run install
> 
>                     workingDir=/Users/Piipperi/Apple-Music-Electron/node_modules/@seorii/win32-displayconfig
> 
> error Command failed with exit code 1.
> 
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> ```
> 

Use node 14.18.1 
https://github.com/nodejs/node-gyp/issues/2534

**Comment by coredev-uk** [comment]
As I said, run `npm i --openssl_fips=X` then `npm run dist` or `yarn dist`

**Comment by Piipperi** [comment]
> As I said, run `npm i --openssl_fips=X` then `npm run dist` or `yarn dist`

Tried this, didn't work. Still the same errors rise.

**Comment by coredev-uk** [comment]
hmm

**Comment by coredev-uk** [comment]
Try deleting `node_modules` and run: `npm i --openssl_fips=X` then `npm run dist --openssl_fips=X`

**Comment by Piipperi** [comment]
> Try deleting `node_modules` and run: `npm i --openssl_fips=X` then `npm run dist --openssl_fips=X`

```
Epic-Gamer-MacBook:Apple-Music-Electron Piipperi$ npm i --openssl_fips=X
npm ERR! code 1
npm ERR! path /Users/Piipperi/Apple-Music-Electron/node_modules/audify
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run rebuild
npm ERR! > audify@1.6.3 rebuild
npm ERR! > cmake-js compile
npm ERR! 
npm ERR! [
npm ERR!   '/usr/local/bin/node',
npm ERR!   '/Users/Piipperi/Apple-Music-Electron/node_modules/.bin/cmake-js',
npm ERR!   'compile'
npm ERR! ]
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=17.0.1 runtime=node arch=x64 libc= platform=darwin)
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info REP Build has been failed, trying to do a full rebuild.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Piipperi/.npm/_logs/2021-11-09T18_29_07_284Z-debug.log
```

**Comment by coredev-uk** [comment]
@vapormusic did say that he removed audify. However, if this continues install cmake. Either through homebrew or using their [website](https://cmake.org/install/).

**Comment by Piipperi** [comment]
> @vapormusic did say that he removed audify. However, if this continues install cmake. Either through homebrew or using their [website](https://cmake.org/install/).

> Try deleting `node_modules` and run: `npm i --openssl_fips=X` then `npm run dist --openssl_fips=X`

These two worked, installed cmake from Homebrew and ran npm I --openssl_fips=X and npm run dist --openssl_fips=X

**Comment by Piipperi** [comment]
Well it works now, except with all Apple Music songs I get a "MEDIA_LICENSE" error (yet songs from Cloud Library work fine)

**Comment by coredev-uk** [comment]
Yeah, that's Widevine. Since we don't have a signed app it can never authenticate. Until we can get the app signed, which I believe is done using a $100 development license, the macOS Application will not work. I'll update this thread if any updates occur in this sense.
