### ISSUE TITLE
[BUG] Cannot open AME 3.0.0 if closed.

### ISSUE THREAD

**Issue by DoctorAnon** [Apple-Music-Electron/Apple-Music-Electron#361]
**Describe the bug**
When closing AME via the normal in-application close button, you cannot open AME via your task bar unless you go to task manager and close the running AME processes, or go to system tray > AME icon > right click > quit

**To Reproduce**
1. Open AME
2. Exit the application by pressing the top right/left red/x button.
3. Attempt to launch AME again
4. It does not launch

**Expected behavior**
Upon closing AME & clicking to open the application, it should just open.

**Environment Information**
 - OS *Windows 11*
 - Application Version *3.0.0* 
 
**Additional context**
The work-around is to manually close AME via system tray or to end the AME processes in task manager (even tho there is no visible AME application)

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
Yes

**Log File**
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7510502/main.log)

**Comment by coredev-uk** [comment]
Do you have closeButtonMinimize on?

**Comment by DoctorAnon** [comment]
> Do you have closeButtonMinimize on?

When having minimize on, it acts as expected. But no, I do not have it on as it's not enabled by default - and it shouldn't be. Without closeButtonMinimize on it should just close the application completely - which it doesn't as there are still processes running in task manager, and you cannot reopen AME until you close those processes
