### ISSUE TITLE
[BUG] Restart Dialog isn't showing

### ISSUE THREAD

**Issue by rhonXD** [Apple-Music-Electron/Apple-Music-Electron#371]
**Describe the bug**
The restart dialog doesn't show when changing something under preferences such as:
- application frame
- transparency effect

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 
 - Application Version *(e.g. 2.5.0)*: 3.0.0
 
**Additional context**
I tried quitting the application after changing settings just in case it may apply, yet to no avail.

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Comment by coredev-uk** [comment]
Transparency affect is applied whenever you change is, so should app frame.

**Comment by certifiedgeek** [comment]
Doesn't show up for me either. And the applied settings reset back each time the app is restarted...

**Comment by rhonXD** [comment]
I found a workaround, just add the themes folder on app data and it will
work

**Comment by coredev-uk** [comment]
Is this occurring on the latest release? As after 3.0.0 was released the files were updated with a fix for themes not installing.

**Comment by certifiedgeek** [comment]
> Is this occurring on the latest release? As after 3.0.0 was released the files were updated with a fix for themes not installing.

downloaded the new UPDATED app nd works just fine... deleted the %appdata%/Apple Music and then re installed the updated software and everything's working perfectly!

**Comment by coredev-uk** [comment]
Glad to hear it.
