### ISSUE TITLE
[BUG] "Apple Color Emoji" causes incorrect word spacing on all pages and elements

### ISSUE THREAD

**Issue by btglr** [Apple-Music-Electron/Apple-Music-Electron#374]
**Describe the bug**
Words are spaced out way too much.

**To Reproduce**
1. Use the Developer Tools and select any element with text
2. Find the `html` selector with the `font-family` property
3. Set "Apple Color Emoji" as the first font i.e. `"Apple Color Emoji","SF Pro","SF Pro Icons","Helvetica Neue",Helvetica,Arial,sans-serif`

**Expected behavior**
Words are spaced out normally.

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/37577064/142242473-1e100ad9-09d0-4379-bc69-d078801ac75b.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Arch Linux
 - Application Version *(e.g. 2.5.0)*: compiled from master branch
 
**Additional context**
Changing the `font-family` property from `-apple-system,BlinkMacSystemFont,"Apple Color Emoji","SF Pro","SF Pro Icons","Helvetica Neue",Helvetica,Arial,sans-serif` to `-apple-system,BlinkMacSystemFont,"SF Pro","SF Pro Icons","Helvetica Neue",Helvetica,Arial,sans-serif` fixed the problem in my case:

![Screenshot_7](https://user-images.githubusercontent.com/37577064/142242938-74d37026-e1a7-4a4f-ad8e-bcdba38bd28a.png)

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Comment by booploops** [comment]
This explains a lot

**Comment by booploops** [comment]
Under the devtools, what is the "platform" attribute set to on the body tag?

**Comment by btglr** [comment]
> Under the devtools, what is the "platform" attribute set to on the body tag?

It's set to Linux x86_64

**Comment by booploops** [comment]
I just pushed a commit to test this out, give it a try.

**Comment by btglr** [comment]
Fixed! That was quick haha. Thank you!
