### ISSUE TITLE
[BUG] The entire window presents a white screen.

### ISSUE THREAD

**Issue by jay900604** [Apple-Music-Electron/Apple-Music-Electron#378]
**Describe the bug**
The entire window presents a white screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/46503943/142721200-c269307d-a411-4d4a-a07b-4b917aa54c58.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 11
 - Application Version *(e.g. 2.5.0)*: 3.0.0
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
No

**Comment by Void48** [comment]
Same issue as me

**Comment by dafterside** [comment]
go to AppData/Roaming and delete the AppleMusic folder, that worked for me

**Comment by Void48** [comment]
> go to AppData/Roaming and delete the AppleMusic folder, that worked for me

this didn't work for me. tried it before

**Comment by vapormusic** [comment]
We updated the releases with the exe that should fix this issue. Someone on discord has the same issue and no longer has blank screen on new build. 
P/S  : just for sure , please clear the %AppData%/AppleMusic folder before running the new exe
