### ISSUE TITLE
[BUG] Settings go back button bug

### ISSUE THREAD

**Issue by Skyterix1991** [Apple-Music-Electron/Apple-Music-Electron#380]
**Describe the bug**
Account settings and preferences tabs both have bugged back button on the top left. It will go back after two clicks, additionally if you click ex. account settings a few times, it will add another two clicks each time you entered the account settings. Ex. If you click account settings 4 times, the back button will have to be clicked 8 times to go back.

**To Reproduce**
1. Go to account settings
2. Go to account settings again while the current account settings screen is open
3. Start clicking the back button
4. It will require 4 clicks to fully close it.

**Expected behavior**
Any settings view should only be opened once, every other attempt should either reset the view or just do nothing. And the back button should not require two clicks but one.

**Environment Information**
 - OS: Linux Manjaro GNOME 41.1 X11
 - Application Version: 3.0.0-2 from AUR

**Comment by coredev-uk** [comment]
The back button shouldn't appear on the settings page. Should be good now.
