### ISSUE TITLE
[BUG] Error while building: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by linuxct** [Apple-Music-Electron/Apple-Music-Electron#395]
**Describe the bug**
While building from the AUR, the build throws an error, twice. 

**To Reproduce**
1. Attempt to clean-build the package from the AUR 'apple-music-electron-git-3.0.0-2'.
2. The error appears at build stage 4/4 and the build stops.

**Expected behavior**
The application builds normally.

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Arch Linux
 - Application Version *(e.g. 2.5.0)*: latest git commit
 
**Additional context**
See the log attached. [yarnlog-20211127.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7612238/yarnlog-20211127.log)
This might be related: https://github.com/electron/electron-rebuild/issues/913

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Attached the full yarn build log.
[yarnlog-20211127.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7612238/yarnlog-20211127.log)

**Comment by linuxct** [comment]
Also relevant: https://github.com/nodejs/node-gyp/issues/2534

**Comment by linuxct** [comment]
I tried manually upgrading my node-gyp install to 8.4.1 by modifying the PKGBUILD available here https://github.com/archlinux/svntogit-community/blob/packages/node-gyp/trunk/PKGBUILD. Prebuilt also attached for reference: [node-gyp-8.4.1-1-any.pkg.tar.zip](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7612293/node-gyp-8.4.1-1-any.pkg.tar.zip). 

This way I got the latest node-gyp, which according to my previous comment should have fixed the issue. But the issue still remains.  

Fresh logs attached.
[yarnlog-20211127-02.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7612288/yarnlog-20211127-02.log)

**Comment by coredev-uk** [comment]
I did comment on the AUR regarding this issue, I suggest you use your current version or use the -bin package. I will close this issue until any further developments occur.
