### ISSUE TITLE
[BUG] cannot open Preference tab

### ISSUE THREAD

**Issue by Ray-Eldath** [Apple-Music-Electron/Apple-Music-Electron#401]
**Describe the bug**
When clicked _Preference_ on the dropdown, the page will go to "Listen Now". _Preference_ page won't show up.

**To Reproduce**
1. Click the dropdown on the right 
2. Click on 'Preference'
4. "Listen Now" shows up, instead of expected _Preference_.

**Expected behavior**
_Preference_ tab shows up.

**Screenshots**

https://user-images.githubusercontent.com/7938763/144224172-8c8f8a83-fb51-49ab-8e43-9683a762e12d.mp4

**Environment Information**
 - OS: Manjaro KDE (Linux manjaro 5.10.79-1-MANJARO)
 - Application Version: `apple-music-electron-git 3.0.0.1278.5b8c5c6-1`
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7633315/main.log)

**Comment by zbodo** [comment]
Windows11 _22000.318_ 同样存在此bug

**Comment by vapormusic** [comment]
Hmm, this seems to be a new issue for some Chinese users. I believe you can fix this by delete the %Appdata%/AppleMusic folder.

https://github.com/Apple-Music-Electron/Apple-Music-Electron/issues/399#issuecomment-983232002
https://github.com/Apple-Music-Electron/Apple-Music-Electron/issues/399#issuecomment-983330919

**Comment by zbodo** [comment]
> 

我已经尝试过很多次，但完全不起作用
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7641655/main.log)

**Comment by Ray-Eldath** [comment]
> Hmm, this seems to be a new issue for some Chinese users. I believe you can fix this by delete the %Appdata%/AppleMusic folder.
> 
> [#399 (comment)](https://github.com/Apple-Music-Electron/Apple-Music-Electron/issues/399#issuecomment-983232002) [#399 (comment)](https://github.com/Apple-Music-Electron/Apple-Music-Electron/issues/399#issuecomment-983330919)

I tried many times, including clean install, and no avail. :cry:

**Comment by vapormusic** [comment]
Oof, let me check it

**Comment by vapormusic** [comment]
This should be fixed by #410

**Comment by zbodo** [comment]
> This should be fixed by #410 The releases have been updated with the fix.

我试用了他 但现在仍有新的BUG
![GIF 2021-12-6 11-01-59](https://user-images.githubusercontent.com/39948021/144780321-c53d5534-f7b8-4c17-b7c1-45fc7bf3853b.gif)

**Comment by vapormusic** [comment]
@zbodo  are you living in China (PRC) ?

**Comment by zbodo** [comment]
> @zbodo are you living in China (PRC) ? A better way is go to beta.apple.music.com and click on made for you page then screenshot it here

Yes I'm living in China.
 beta.music.apple.com ?
![image](https://user-images.githubusercontent.com/39948021/144783009-54bcfbb0-17e0-4946-829e-a06abd2a8939.png)

**Comment by vapormusic** [comment]
> > @zbodo are you living in China (PRC) ? A better way is go to beta.apple.music.com and click on made for you page then screenshot it here
> 
> Yes I'm living in China. beta.music.apple.com ? ![image](https://user-images.githubusercontent.com/39948021/144783009-54bcfbb0-17e0-4946-829e-a06abd2a8939.png)

Is the exe in  https://github.com/vapormusic/Apple-Music-Electron/releases/tag/cn-fx working ?

**Comment by zbodo** [comment]
> > > @zbodo are you living in China (PRC) ? A better way is go to beta.apple.music.com and click on made for you page then screenshot it here
> > 
> > 
> > Yes I'm living in China. beta.music.apple.com ? ![image](https://user-images.githubusercontent.com/39948021/144783009-54bcfbb0-17e0-4946-829e-a06abd2a8939.png)
> 
> Is the exe in https://github.com/vapormusic/Apple-Music-Electron/releases/tag/cn-fx working ?

仍然不起作用

**Comment by zbodo** [comment]
@Ray-Eldath 你那里已经不出问题了吗？

**Comment by vapormusic** [comment]
@zbodo go to %AppData%/AppleMusic , open config.json and setBetaSite to false

**Comment by zbodo** [comment]
> @zbodo go to %AppData%/AppleMusic , open config.json and setBetaSite to false
> 
> I cant fully diagnose this as i don't have a Chinese phone number and can't make a Chinese Apple ID

修改后甚至点击头像不出现任何反应了

**Comment by zbodo** [comment]
@vapormusic 如果非常难以解决的话也可以搁置到以后再想办法修复。

**Comment by rtw0424** [comment]
@vapormusic Same bug occurs in Korea. (If I click on preferences, it goes to 'Now Listen')
