### ISSUE TITLE
[Enhancement] Discord RPC Shows Album Cover instead of Apple Music Logo

### ISSUE THREAD

**Issue by devilAPI** [Apple-Music-Electron/Apple-Music-Electron#73]

**Comment by cryptofyre** [comment]
Impossible to make happen as Discord's GameSDK does not allow it by regular circumstances.

**Comment by devilAPI** [comment]
damn.. should this issue be closed?

**Comment by coredev-uk** [comment]
Might as well leave it open until Discord gets back to us about this.

**Comment by child-duckling** [comment]
Closing to consolidate the issues

**Comment by Smaltin** [comment]
Could use similar methods to https://github.com/jojo2357/Music-Discord-Rich-Presence and/or make usage of https://github.com/jojo2357/Music-Discord-Rich-Presence-Library

**Comment by coredev-uk** [comment]
Manually adding each album image is not the way we're looking to implement this. We could allow users to set their client id for those who only listen to a small number of albums.
